### ISSUE TITLE
Sudan (SD) missing address data

### ISSUE THREAD

**Issue by vapier** [googlei18n/libaddressinput#103]
no data is found for Sudan (territory code SD):
https://i18napis.appspot.com/address/data/SD

**Comment by vwmax** [comment]
Looking into this. 
32446329. ai/md

**Comment by F21** [comment]
Address format here: http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/sdnEn.pdf

**Comment by bojanz** [comment]
Seems to have been added: https://chromium-i18n.appspot.com/ssl-address/data/SD

Still missing administrative areas.

**Comment by mimckenna** [comment]
Note that SD has not moved to the gstatic pages yet:
* https://chromium-i18n.appspot.com/ssl-address/data/SD - OK
* https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/SD - 404 error

**Comment by madmath** [comment]
Thanks for pointing this out, @mimckenna. Sudan was added to gstatic, but I would insist that people still use URLs like https://chromium-i18n.appspot.com/ssl-address/data/SD and not point to gstatic directly, as this case illustrates
