### ISSUE TITLE
Cuba (CU) missing address data

### ISSUE THREAD

**Issue by vapier** [googlei18n/libaddressinput#105]
no data is found for Cuba (territory code CU):
https://i18napis.appspot.com/address/data/CU

**Comment by vwma** [comment]
Refreshing this thread. Taking a look. 
32442523. ai/md

**Comment by F21** [comment]
Address format here: http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/cubEn.pdf

**Comment by bojanz** [comment]
Seems to have been added: https://chromium-i18n.appspot.com/ssl-address/data/CU

Still missing subdivisions (administrative areas).

**Comment by vwmax** [comment]
This should be fixed now. Subdivisions added for CU.

**Comment by F21** [comment]
@vwmax There are still no subdivisions at https://chromium-i18n.appspot.com/ssl-address/data/CU

**Comment by madmath** [comment]
Server was updated, thanks!
