### ISSUE TITLE
South Korean postal code format has changed

### ISSUE THREAD

**Issue by camertron** [googlei18n/libaddressinput#111]
According to [an issue](https://github.com/twitter/twitter-cldr-rb/issues/195) filed against twitter-cldr-rb, postal codes in South Korea have changed from 6 digits to 5. I believe the [appspot API](http://i18napis.appspot.com/address/data/KR) data needs to be updated with this change.

Is there anything I can do to speed this process along?

**Comment by sockix** [comment]
Currently the widget accepts both 5 digit and 6 digit postal codes.  We will be deprecating support for 6 digit postal codes in the near future.  I'll update this issue and close it out once we do.

**Comment by sockix** [comment]
Thanks for the feedback. 

Closing this bug out regex for South Korea has been updated and it's now reflected in the data served from Chromium.
