### ISSUE TITLE
Guam (GU) does not have administrativeArea

### ISSUE THREAD

**Issue by josephzidell** [googlei18n/libaddressinput#115]
Guam (GU) does not have administrative areas, or states. This is causing issues. Can it be removed and not marked as required? [Wikipedia](https://en.wikipedia.org/wiki/List_of_populated_places_in_Guam)

**Comment by sockix** [comment]
Thanks for the feedback.  Apologies. We are currently looking into this, and similar issues.  I'll update this issue when state is no longer being requested.

**Comment by josephzidell** [comment]
@sockix Any update?

**Comment by sockix** [comment]
Hi Joseph, 

Apologies, this has been updated. You shouldn't be seeing state as a required field.
