### ISSUE TITLE
Valid GB postcodes failing postcode regex validation.

### ISSUE THREAD

**Issue by maseyuk** [googlei18n/libaddressinput#123]
Certain UK post codes are getting marked as invalid when they are in fact genuine postal code. 
E.g. EC1V OBW is a valid postcode but I think the current GB regex doesn't match for this

**Comment by mimckenna** [comment]
Hi,

we're running into a postcode regex problem for GB with BFPO postcodes (British Forces)

According to [Royal Mail](http://www.royalmail.com/postcode-finder-address-enquiry-form), given the postcode `BF1 2AY`, it comes back with the address:
```
BFPO 61
BFPO
BF1 2AY
```
libaddressinput validation data can handle the `BFPO 61` as a postcode, but not `BF1 2AY`

It looks like `BF` postcodes for [BFPO British Forces Mail was added in 2012](https://www.poweredbypaf.com/wp-content/uploads/2015/12/Introduction-to-bfpo-data1.pdf), but the [source data](http://i18napis.appspot.com/address/data/GB) has not been updated yet.

Old pattern
```
"zip": "GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}"
```

Proposed New Pattern, add "BF"
```
"zip": "GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BF|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}"
```

**Comment by madmath** [comment]
Thanks! The "BF" issue has been fixed: https://chromium-i18n.appspot.com/ssl-aggregate-address/data/GB
