### ISSUE TITLE
LI missing 9498 as valid postcode

### ISSUE THREAD

**Issue by mimckenna** [googlei18n/libaddressinput#131]
In Liechtenstein, 9498 is the postal code for Planken, But the [i18napis data for LI](http://i18napis.appspot.com/address/data/LI) shows a postal code validation pattern of
```
"zip": "948[5-9]|949[0-7]
```
Which will not allow 9498.

Sources:
GRCD:  [Postal code formats](https://www.grcdi.nl/gsb/liechtenstein.html#H12AAD60A0A15534EABC27B3719E3A17C0F60362803CA2AA2ALiechtensteinA20A2DA20A5BA5BPostalA20codesA5DA5DA2AA2A00100401401701A01D02002903103403703A)
[TNT Europe](https://www.tnt.com/express/en_lu/site/home/applications/searc_postcode.html)
Wikipedia (German): https://de.wikipedia.org/wiki/Postleitzahl_(Schweiz)#Liechtensteiner_Postleitzahlen 
Wikipedia article on Planken, LI: https://en.wikipedia.org/wiki/Planken 
Swiss post postcode search service: https://www.post.ch/en/pages/plz-suche - search for "Planken"

Note that according to Swiss Post, 9489 does not exist as a postcode.

Perhaps the validation pattern should be:
```
"zip": "948[5-8]|949[0-8]
```

Mike McKenna

**Comment by madmath** [comment]
Thanks! This has been fixed, see https://chromium-i18n.appspot.com/ssl-aggregate-address/data/LI (which is the new server that we keep up to date)
