### ISSUE TITLE
Missing 'lang' field for many countries

### ISSUE THREAD

**Issue by ehom** [googlei18n/libaddressinput#136]
Hi,

I noticed that the 'lang' field (as well as 'languages') is absent in the address metadata for many countries.

For instance:

https://chromium-i18n.appspot.com/ssl-address/data/AT

```
{
  "zipex": "1010,3741", 
  "name": "AUSTRIA", 
  "zip": "\\d{4}", 
  "fmt": "%O%n%N%n%A%n%Z %C", 
  "require": "ACZ", 
  "key": "AT", 
  "posturl": "http://www.post.at/post_subsite_postleitzahlfinder.php", 
  "id": "data/AT"
}

```

lang: "de"   ????

----

Here are some of those countries:

AC, AF, AG, AI, AL, AO, AQ, AS, AT, AW, AX, AZ, ...

CH, DE, FR

If this is really an issue, I'll provide the complete list.

**Comment by sockix** [comment]
This seems to be working as intended. 

I believe 'lang' and 'languages' are only included when there are administrative areas defined for the country. For example, if you look at 'US' or 'IN'.

**Comment by ehom** [comment]
Thanks.

I see the explanation now.

> https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata
>
> Checking for Sub-Regions:
