### ISSUE TITLE
Bad Link on AddressValidationMetadata Wiki Page

### ISSUE THREAD

**Issue by ehom** [googlei18n/libaddressinput#137]
https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata

In section **Programmatically using the data:**

> For more information, visit the website:
>
> https://github.com/googlei18n/libaddressinput/tree/master/java

^^^^^^^^^

Should it be: 

> https://github.com/googlei18n/libaddressinput/tree/master/android

???

**Comment by madmath** [comment]
cc @sebsg do you have access to the wiki to edit this?

**Comment by sebsg** [comment]
It should be fixed now, thanks for the report!
