### ISSUE TITLE
Issues with Guam Zip Code Regular Expression

### ISSUE THREAD

**Issue by ivanoxq** [googlei18n/libaddressinput#150]
Hi Guys,

The data coming back from data/US/GU has regular expression "969([1-2]\\d|3[12])" which needs to be changed to 969([1-2]\\d|3[012]) as its missing the recognition of Talofofo, Guam 96930.

**Comment by sockix** [comment]
Hi. Thank you for the feedback. 

Do you have an example address which you expect the 96930 to work with?  As far as I can tell, Talofofo should use the 96915 as it's postal code.

**Comment by sockix** [comment]
See: 
https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=96930&zip=

ivanoxq@ I'm going to close this issue, but feel free to reopen if you disagree with my findings.  Thx.
