### ISSUE TITLE
Postal code pattern for IN/Puducherry

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#151]
Copied from: https://github.com/commerceguys/addressing/pull/84

The user says that the postal_code pattern for Puducherry should be changed from "605" to "60", based on https://pincode.net.in/PONDICHERRY/KARAIKAL/K/KARAIKAL.

Unconfirmed.

**Comment by sockix** [comment]
Thanks for pointing this out.

I have also verified that the current regex is too restrictive using www.indiapost.gov.in.

**Comment by sockix** [comment]
As far as I can tell from the India Post website, all of the valid PIN codes begin with either 605, 607 or 609. 

The regex has been updated to reflect that.
