### ISSUE TITLE
chromium-18n.appspot.com is redirecting to gstatic.com and no longer returns CORS headers

### ISSUE THREAD

**Issue by lucastetreault** [googlei18n/libaddressinput#152]
Can't access https://chromium-i18n.appspot.com/ssl-address/data/CA anymore. This now redirects to https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/CA which does not return CORS headers. My application is broken!

**Comment by madmath** [comment]
Hi, very sorry about that. Let me see about reverting this change. 

Can you specify which CORS header you're expecting?

Here are some of the headers on the gstatic location
```
GET /chrome/autofill/libaddressinput/chromium-i18n/ssl-aggregate-address/data/CA HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.gstatic.com
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: none
< Vary: Accept-Encoding
< Content-Type: text/plain; charset=UTF-8
< Access-Control-Allow-Origin: *
```

**Comment by lucastetreault** [comment]
Hey, thanks for the quick reply! 

We were looking in to this some more and realized it's not the gstatic url that doesn't return 'Access-Control-Allow-Origin: *' it's https://chromium-i18n.appspot.com/ssl-address/data/CA when it sends the redirect that doesn't return any access control header.

I hope that helps.

**Comment by madmath** [comment]
OK upon further research it seems that even the redirecting URL must contain the CORS header. Let me make fixes on the chromium-i18n-canary instance and report back for testing, Lucas. 

In the meantime I'm reverting the changes on https://chromium-i18n.appspot.com (should be effective soon)

**Comment by lucastetreault** [comment]
You are a rockstar. Thanks so much for the quick action!

**Comment by madmath** [comment]
Hello, could you try with https://chromium-i18n-canary.appspot.com/ssl-address/data/CA (which has the redirect-CORS fix applied) and report whether it works?

**Comment by madmath** [comment]
Ping @lucastetreault

**Comment by lucastetreault** [comment]
Woops sorry about the delay! I was in a meeting this morning when I noticed your first comment and totally forgot to check it out by the time the meeting was over... 

I just tried with https://chromium-i18n-canary.appspot.com/ssl-address/data/CA and it's working beautifully. 

Thanks again for your help with this :)

**Comment by madmath** [comment]
Update: https://chromium-i18n.appspot.com is now fixed and the preferred way to use this API
