### ISSUE TITLE
GetRegionDataKeyForValue returns incorrect region key

### ISSUE THREAD

**Issue by userdsod** [googlei18n/libaddressinput#154]
https://github.com/googlei18n/libaddressinput/blob/5764685e7ca0dc410c535dba3bad29f703e78c32/android/src/main/java/com/android/i18n/addressinput/AddressWidget.java#L231

There are certain display strings that end with the same thing. the specific instance I encountered was trying to get the key for Netherlands ("NL") and this function returning the key for Caribbean Netherlands ("BQ"). other examples of this particular issue are Samoa and American Samoa.

**Comment by mountaingoatx** [comment]
This bug should now be fixed.
