### ISSUE TITLE
Canada updates

### ISSUE THREAD

**Issue by adrianbj** [googlei18n/libaddressinput#165]
Currently there is no value for `state_name_type`, but it should be set to `province`. 

Also, I think `sublocality_name_type` should be set to `city` or perhaps `city/town`

Thanks!

**Comment by sockix** [comment]
Hi. 

Province is assumed to be the default value, so it's generally not explicitly set in the state_name_type.
Likewise, I believe that 'city' is the default for locality_name_type, so it really doesn't matter if it's set or not.
There is no sublocality in Canada, so there's no need for sublocality_name_type.
