### ISSUE TITLE
Canada, Nunavut, Kuujjuaq, J0M 1C0

### ISSUE THREAD

**Issue by ncg777w** [googlei18n/libaddressinput#171]
Hi! I'm not a direct user of this library, but I've been told a drupal module I'm using for addresses is based on it.

I have a postal code in Kuujjuaq which does not match the rules set for Nunavut. It is J0M 1C0.

According to this post canada page, this postal code really is located in Kuujjuaq: https://www.canadapost.ca/cpo/mc/personal/postalcode/fpc.jsf

It is a P.O. Box.

**Comment by sockix** [comment]
Hi. I'm confused what you are indicating. 

Isn't 'Kuujjuaq' located in the province of Quebec?  If so, 'J0M 1C0' seems valid for Quebec and should work fine in the widget.

**Comment by ncg777w** [comment]
Gosh. You are right. That was the mistake! Thanks a lot.
