### ISSUE TITLE
Countries that need postal codes

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#46]
Unsure if this is the right place to discuss dataset bugs or insufficiencies, also posted in https://groups.google.com/forum/#!topic/libaddressinput-discuss/uDVRwyMxZpQ

Some countries have no postal code in their formats, despite conflicting online information.

Albania 
https://en.wikipedia.org/wiki/Postal_codes_in_Albania
http://www.en.postashqiptare.al/Services/PostalServices/PostalCode.aspx

St. Vincent & Grenadines (VC)
http://www.svgpost.gov.vc/index.php?option=com_content&view=article&id=3&Itemid=7
http://www.addressdoctor.com/en/company/news-events/news-details-news/article/st-vincent-and-the-grenadines-introduce-postal-codes.html

Barbados (BB): https://en.wikipedia.org/wiki/List_of_postal_codes_in_Barbados

Peru: https://en.wikipedia.org/wiki/List_of_postal_codes_in_Peru
"The postal code format in Peru was updated in February 2011 to be of the format NNNNN (five digits).”

**Comment by mimckenna** [comment]
:+1: non adding Albania.

Also, the regex for Tanzania (TZ) is incorrect.  The patterns in ​http://www.tcra.go.tz/index.php/publication-and-statistics/postcode-list indicate the regex should be "[1-7]\d{4}"

**Comment by bojanz** [comment]
Looks like Barbados has been fixed: https://i18napis.appspot.com/address/data/BB

**Comment by lararennie** [comment]
A fix is in progress for the other countries.
As for Tanzania, we support both old and new format currently (but are a bit lenient on the new format, we allow 5 digits, this could be tightened). Could you file a new github issue to track Tanzania so we can move to the new format only? Thanks!

**Comment by lararennie** [comment]
Main issue fixed.

Tanzania: please file a github issue about this separately.
