### ISSUE TITLE
Ordering of Mexican provinces, name of the "Mexico" province

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#49]
1) The wikipedia page on MX ISO codes says:
"Subdivision names are sorted in traditional Spanish alphabetical order: a-c, ch, d-l, ll, m-n, ñ, o-z."
This traditional ordering is also used by UPU, but not by the dataset.

Expected sorting:
Campeche - Coahuila - Colima - Chiapas - Chihuahua
Dataset sorting:
Campeche - Chiapas - Chihuahua - Coahuila - Colima

2) "Estado de México" should be just "México" (and ordered appropriately), as demonstrated by both ISO and UPU.

https://en.wikipedia.org/wiki/ISO_3166-2:MX
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/mexEn.pdf

**Comment by lazaa** [comment]
The display name of the "MEX" subdivision is still not fixed. In addition (per ISO) there is typo in the name of SIN and SLP too:

Per ISO:
MEX	**México**
SLP	San Lu**i**s Potosí
SIN	Sinal**o**a

**Comment by bojanz** [comment]
The new name for DIF is now "Ciudad de México": http://www.dif.cdmx.gob.mx/

**Comment by vwmax** [comment]
Looking into this. 
73079601. ai/md

**Comment by bojanz** [comment]
The SLP and SIN misspellings have been fixed. 
DIF now has the correct name and ISO code (CDMX).

The name for MEX still isn't fixed, same for the sorting.

**Comment by mountaingoatx** [comment]
Closing this issue since all the other changes have been made. Feel free to reopen if you don't think it's adequately addressed!

**Comment by bojanz** [comment]
@mountaingoatx I don't understand how the Wikipedia article is an argument for refusing the MEX rename. Instead, look at the ISO list, where the rename happened: https://www.iso.org/obp/ui/#iso:code:3166:MX
