### ISSUE TITLE
Missing address format, subdivisions for Peru

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#50]
The subdivisions are listed on the UPU document:
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/perEn.pdf
#46 already confirmed that Peru needs postal codes.

The UPU document also mentions a sublocality field, but no locality field. 
I [geocoded](https://maps.googleapis.com/maps/api/geocode/json?address=Av.%20Larco%201301,%20Miraflores,%20Lima,%20Peru) the sample address and it placed Miraflores into "locality".
A quick wikipedia / google search also tells me that the correct label for this field is "District":
https://en.wikipedia.org/wiki/Miraflores_District,_Lima

**Comment by JohnatasJMO** [comment]
Peru needs postal codes. The right way is:

Administrative Area = Department
Locality = Province
Dependant Locality = District
Postal Code = Postal Code


There is also a sub-locality which seems like it is not longer used and to be replaced by postal code.  I have asked for the list to the national postal service in Peru.

http://www.codigopostal.gob.pe/pages/invitado/consultaSimple.jsf
http://www.codigopostal.gob.pe/index.html

<img width="506" alt="screen shot 2017-04-27 at 10 18 33 am" src="https://cloud.githubusercontent.com/assets/2703508/25474287/f7c1588e-2b32-11e7-8657-8d874ad3c3eb.png">

<img width="1115" alt="screen shot 2017-04-27 at 10 21 08 am" src="https://cloud.githubusercontent.com/assets/2703508/25474376/497f2584-2b33-11e7-8123-deaa1a9a7f9b.png">

**Comment by lararennie** [comment]
Peru data already asks for a post code and allows the new format (5 digits) or the old format (Lima 23, Lima 42, Callao 2 etc). What precise change are you requesting?

**Comment by bojanz** [comment]
At minimum, we need to add a list of administrative areas for Peru.

Other suggested changes are:
- Adjust state_name_type (to Department)
- Adjust sublocality_name_type (to District)
- Remove locality field.

**Comment by vwmax** [comment]
The form now shows "District." 
We checked with locale experts for Peru and received differing responses w/r/t changing to "Department," so we're holding off on making that change.
