### ISSUE TITLE
Updated ISO code for an Indian state (UL -> UT)

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#54]
On 2011-12-15 ISO issued the following update:
IN-UL Uttaranchal → IN-UT Uttarakhand

The name is already correct in the dataset, the ISO code just needs to be updated.

http://www.iso.org/iso/iso_3166-2_newsletter_ii-3_2011-12-13.pdf

**Comment by andyst** [comment]
Sorry, for the slow reply here. The issue has been fixed.

**Comment by bojanz** [comment]
Big thanks for fixing these issues! Never too late.
