### ISSUE TITLE
Add the Town/City locality type

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#57]
According to my previous addressing dataset (gathered with the help of our clients), United Kingdom and New Zealand (GB, NZ) use the "Town/City" label for the locality.

Google's dataset currently specifies "post town" for GB, which matches what UPU is saying.
However, Royal mail itself uses "City or town" on their own site:
https://dl.dropboxusercontent.com/u/10724055/royalmail.png

For New Zealand the situation is more clear, UPU uses "Town/City":
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/nzlEn.pdf
And so does the site of the New Zealand post:
https://dl.dropboxusercontent.com/u/10724055/nzpost.png

**Comment by sockix** [comment]
Going through some of these older reported issues... I believe that GB/UK and NZ are currently modeled correctly. 

In GB we display a Post Town field
In NZ we display both Suburb and City fields
