### ISSUE TITLE
Indonesian labels

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#60]
The state_name_type and locality_name_type for Indonesia need to change.
The state_name_type should be removed, so that it defaults to "province".
The locality_name_type should be set to a newly added "city_regency".

The dataset currently lists the state_name_type as "district":
https://i18napis.appspot.com/address/data/ID

According to Wikipedia and UPU, the state is "Province", the locality is "City/Regency", and the dependent locality is "District".

An odd detail is that UPU says that the provinces aren't used for mailing, but both your dataset and my previous one contain Indonesian provinces. That requires additional research.
UPU also mentions dependent localities, but the dataset currently doesn't specify that field being used (looks like it's rare?)

http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/idnEn.pdf
https://en.wikipedia.org/wiki/List_of_regencies_and_cities_of_Indonesia

**Comment by dlyongemallo** [comment]
The state name type has been removed as of https://github.com/googlei18n/libaddressinput/pull/95.

**Comment by bojanz** [comment]
Thanks! That means we're 50% done

**Comment by vwmax** [comment]
With regard to #3 "city/regency," changing the field label is not feasible right now. We currently show locality as "City" which users Indonesian users know can be used for "Regency" as well (as confirmed by region specialist we've checked with. Leaving that as is. 
W/r/t #2 "province," we're currently looking into that. Will follow up on that in 
Indonesian provinces not required #164.
