### ISSUE TITLE
Postal code prefixes for Puerto Rico and Slovenia don't match what's in the format

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#72]
https://i18napis.appspot.com/address/data/PR has the prefix listed as "PR", according to the format string and online guidelines, it should be "PR ".

https://i18napis.appspot.com/address/data/SI has the prefix listed as "SI-" but the format uses "SI- ", I was unable to confirm which is preferred.

**Comment by vwmax** [comment]
"PR " is correct. And "SI-" has been updated to eliminate the extra space.

**Comment by bojanz** [comment]
Yes, "PR " is correct, but that's not what the dataset has, it has "PR".
See: https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/PR

**Comment by F21** [comment]
@vwmax Can this be reopened? `postprefix` for `PR` is currently `PR`, but I think it should be `PR ` (with a space).

**Comment by vwmax** [comment]
Reopened. Taking another look. Will circle back.
