### ISSUE TITLE
Subdivisions need unique ids

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#73]
When a subdivision (administrative area / locality / dependent locality) has no ISO id, the library uses the name as the key. This is especially visible for the Brazil localities and China localities / dependent localities. Now, the names of these subdivisions are known to change, causing the "id" to change, and leaving no connection between the old entry and the new entry.
This creates a problem for people wanting to normalize the data by having a "subdivision" table and an "address" table that references subdivisions by id, since subdivision changes leave no way to update the ids in the address table.

In commerceguys/addressing I resorted to generating an id from the sha1 hash of the key (to get a safe value), but that of course doesn't solve the main problem. Recent diff
```
-     "CN-33-6b5326-b2f6e2": {
+    "CN-33-6b5326-a139f5": {
         "locale": "zh-Latn",
         "country_code": "CN",
         "parent_id": "CN-33-6b5326",
-        "id": "CN-33-6b5326-b2f6e2",
-        "code": "绍兴县",
-        "name": "Shaoxing Xian",
+        "id": "CN-33-6b5326-a139f5",
+        "code": "上虞市",
+        "name": "Shangyu Shi",
```
(I am assuming this refers to the same subdivision. I've also seen Brazilian examples where that was more clear).

So, it would be great if the dataset could construct and provide some kind of a unique id, to make it easier for implementations to have the desired datamodel.

**Comment by bojanz** [comment]
From this perspective I don't see how we can invent stable ids, so closing.

**Comment by lararennie** [comment]
Note also ISO IDs change over time, they aren't stable either. And new places pop up, old places disappear, places split up (Serbia and Montenegro became "Serbia" and "Montenegro" respectively) so auto-migrating people is not always possible.

Generally we try and keep the "key" as stable as possible (this is what we think should be saved as part of the address) and the "name" is free to change (it is what should be displayed to the user). This is different for latin-names like China, as you noted.
