### ISSUE TITLE
Lupanshui should be Liupanshui

### ISSUE THREAD

**Issue by tg123** [googlei18n/libaddressinput#82]
http://i18napis.appspot.com/address/data/CN/%E8%B4%B5%E5%B7%9E%E7%9C%81/%E5%85%AD%E7%9B%98%E6%B0%B4%E5%B8%82

`lname` of `六盘水市` should be `Liupanshui`

http://en.wikipedia.org/wiki/Liupanshui

**Comment by dlyongemallo** [comment]
Thanks for letting us know. We'll fix this soon.

**Comment by bojanz** [comment]
Looks like this is now fixed in the dataset?

**Comment by dlyongemallo** [comment]
Yes, it is.

**Comment by bojanz** [comment]
@dlyongemallo
Any chance you could take a look at some of the other issues in this queue as well?
Some of them (like #79 #48 #59 #54) are super simple.

(Not trying to rush, just unsure they've been seen, or whether I missed a step in the workflow)
