### ISSUE TITLE
In Germany the organization comes before the recipient

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#83]
As reported in the PHP reimplementation of libaddressinput: https://github.com/commerceguys/addressing/issues/34

Germany puts the organization before the recipient, just like 28 other countries (including Austria, France, Belgium, Switzerland).

UPU is a bit unclear about this:
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/deuEn.pdf
But the Deutsche post link is authoritative: 
http://www.postadressglobal.com/de-de/country/deutschland/formatierung-und-strukturierung-deutscher-adressen/

**Comment by sockix** [comment]
It is correct that usually the organization should be written before the name of the recipient. However, if the letter is (strictly) confidential and should only be opened by one specific person, the name of the recipient is written before the name of the organization.

Therefore, for business purposes we currently always show the name first.
