### ISSUE TITLE
Correct China Administrative Area data  

### ISSUE THREAD

**Issue by skyred** [googlei18n/libaddressinput#86]
China has 11 Cities/Areas, which don't belong to a Province or State. 

Therefore, when we are querying the data, the **District data** is populated into **City Field**. For example, in the screenshot below,

![image](https://cloud.githubusercontent.com/assets/164034/9878156/f02cd11c-5bf3-11e5-8ce9-85f8fcb785df.png)

"Changning Qu" is populated into the dropdown of the **City Field**. However, "Changning Qu" should be in the **District Field**.

One way to fix this, as also suggested by @bojanz is to duplicate the "administrative area" data, for example, from

> data/CN/Shanghai Shi/Changning Qu

to 

> data/CN/Shanghai Shi/Shanghai Shi/Changning Qu

**Comment by skyred** [comment]
These 11 Cities/Areas are:

5 Autonomous regions (https://en.wikipedia.org/wiki/Autonomous_regions_of_China) :

* Uyghur
* Mongol
* Tibetan
* Hui
* Zhuang

4 Direct-controlled municipalities (https://en.wikipedia.org/wiki/Direct-controlled_municipalities_of_China):

* Beijing
* Shanghai
* Tianjing
* Chongqing

2 Special administrative regions (https://en.wikipedia.org/wiki/Special_administrative_region)

* HongKong
* Macau

**Comment by skyred** [comment]
Below is a screenshot from https://store.google.com, the address format for China is __incorrect__:

![image](https://cloud.githubusercontent.com/assets/164034/11095880/1226003a-88d2-11e5-9934-5cd686bbc352.png)

**Comment by lararennie** [comment]
Hi!

Thanks for this. Actually, we realise it is an issue, not limited to China
but particularly bad there. Unfortunately we have no way at the moment of
changing labels depending on the selected top-level item, which would be
the best way of solving this. But we do have it on our list of
things-to-improve!

Lara


Did you need help with i18n? *Help us help you:* go/i18n-emea-feedback

2015-11-11 17:12 GMT+01:00 Jingsheng Wang <notifications@github.com>:

**Comment by skyred** [comment]
@lararennie At the bottom of the original post, there is a suggestion on how to fix this in data, which doesn't require any of the implementation cross different platforms to change logic/code.

At Drupal, we believe fixing the data is the easiest fix, and we have a plan to implement it in the near future. I was wondering if Google agrees with this approach? If we can collaborate, then we won't need to duplicate effort.

**Comment by lararennie** [comment]
We'd have to look into how that affects usability as well as how it interacts with data already collected, and conversion to/from other formats. It wouldn't be able to be done swiftly.

**Comment by vwmax** [comment]
Looked more into this. Making this change will indeed cause usability problems. We cannot, at this time, make this change.

**Comment by bojanz** [comment]
@vwmax 
What are the usability problems that you're concerned about? Other than backwards compatibility?
I could provide a dataset override on my side, but would like to understand the downsides.
