### ISSUE TITLE
Sorting Code not included in the output of getEnvelopeAddress method

### ISSUE THREAD

**Issue by userar** [googlei18n/libaddressinput#87]
Using the android java library, the `FormatInterpreter` class contains a method `getEnvelopeAddress(AddressData address)` used to get the formatted address. This method does not include the sorting code that may have been set in the `AddressData` object. 

For example French addresses may include a CEDEX. The widget successfully stores the CEDEX value in the sorting code field within `AddressData`, but the field is not included when using `getEnvelopeAddress()` producing an incorrect output.

**Comment by lararennie** [comment]
Thanks for reporting this :)
