### ISSUE TITLE
Required postal codes in CZ, SK

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#88]
A customer reported that CZ and SK have required postal codes, even though the dataset doesn't specify that.

UPU clearly confirms that for SK, but not for CZ, though all examples do have postal codes.
Furthermore, these used to be the same country, so it feels logical that they'd have the same rule.
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/czeEn.pdf
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/svkEn.pdf

The czech post office seems to indicate all addresses have postal codes:
https://www.ceskaposta.cz/en/rady-a-navody/jak-spravne-nadepsat-zasilku

Conclusive enough for me.

**Comment by vwmax** [comment]
This has been updated. 'postal code' now required in CZ and SK.
