### ISSUE TITLE
Swiss administrative areas included but not used?

### ISSUE THREAD

**Issue by bojanz** [googlei18n/libaddressinput#89]
The dataset includes administrative areas (cantons) for Switzerland, but doesn't specify the administrative area field (%S) in the format string.

**Comment by bojanz** [comment]
Actually UPU says that the administrative area field is unused:
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/cheEn.pdf

And the Swiss Post website doesn't include an administrative area dropdown in checkout.

So why are the administrative areas there?

**Comment by andyst** [comment]
Right, they should be removed.
We have to check first whether they can be removed or whether there are other dependencies on this data in our internal code base.

**Comment by andyst** [comment]
Closing this issue.

We no longer serve admin-area (Kanton) data for Switzerland.
http://i18napis.appspot.com/address/data/CH
