### ISSUE TITLE
address metadata in countryinfo.txt appears different compared to what the address data service returns 

### ISSUE THREAD

**Issue by ehom** [googlei18n/libaddressinput#92]
https://github.com/googlei18n/libaddressinput/blob/master/testdata/countryinfo.txt

***
Example 1
--------------

http://i18napis.appspot.com/address/data/AE
returns

{"lang": "ar", "sub_lnames": "Abu Dhabi~Fujairah~Umm Al Quwain~Sharjah~Dubai~Ras al Khaimah~Ajmān", "name": "UNITED ARAB EMIRATES", "require": "AS", "state_name_type": "emirate", "id": "data/AE", "languages": "ar", "lfmt": "%N%n%O%n%A%n%S", "sub_keys": "أبو ظبي~الفجيرة~ام القيوين~إمارة الشارقةّ~إمارة دبيّ~إمارة رأس الخيمة~عجمان", "key": "AE", "sub_isoids": "AZ~FU~UQ~SH~DU~RK~AJ", "fmt": "%N%n%O%n%A%n%S"}

countryinfo.txt:
data/AE={"id":"data/AE","key":"AE","name":"UNITED ARAB EMIRATES","fmt":"%N%n%O%n%A%n%C","require":"AC"}

***
Example 2
--------------

http://i18napis.appspot.com/address/data/HK

{"lang": "zh-hant", "upper": "S", "sub_lnames": "Kowloon~Hong Kong Island~New Territories", "name": "HONG KONG", "sub_mores": "true~true~true", "require": "AS", "state_name_type": "area", "id": "data/HK", "languages": "zh-hant~en", "lfmt": "%N%n%O%n%A%n%C%n%S", "sub_keys": "九龍~香港島~新界", "key": "HK", "locality_name_type": "district", "fmt": "%S%n%C%n%A%n%O%n%N"}

countryinfo.txt

data/HK={"id":"data/HK","key":"HK","name":"HONG KONG","lang":"zh-hant","languages":"zh-hant~en","fmt":"%S%n%A%n%O%n%N","lfmt":"%N%n%O%n%A%n%S","require":"AS","upper":"S","state_name_type":"area","sub_keys":"九龍~香港島~新界","sub_lnames":"Kowloon~Hong Kong Island~New Territories","sub_mores":"false~false~true"}

Differences:
fmt/lfmt values are missing %C
sub_mores values are different
locality_name_type key is missing

***

**Comment by andyst** [comment]
Indeed, we should do a push code / data update to github.

**Comment by dlyongemallo** [comment]
Should be fixed in https://github.com/googlei18n/libaddressinput/pull/95.
