### ISSUE TITLE
Space in GB Postcode Regex should not be Optional

### ISSUE THREAD

**Issue by ehom** [googlei18n/libaddressinput#93]
In the [Royal Mail Programmers Guide] (http://www.royalmail.com/sites/default/files/docs/pdf/programmers_guide_edition_7_v5.pdf), and it states (on page 17):

>The first part, or Outward Code, is **separated** from the second part, the Inward Code, **by a single space**.

And the British Market Research Society (MRS) [guide on postcode format](https://www.mrs.org.uk/pdf/postcodeformat.pdf) says: 

>Leave a clear space of one character between the two parts of the postcode and do not join the characters in any way.

====
Querying the Google Address Data Service for the [GB Address Metadata] (http://i18napis.appspot.com/address/data/GB) returns:
```
{"upper": "CZ", "zipex": "EC1Y 8SY,GIR 0AA,M2 5BQ,M34 4AB,CR0 2YR,DN16 9AA,W1A 4ZZ,EC1A 1HQ,OX14 4PG,BS18 8HF,NR25 7HG,RH6 0NP,BH23 6AA,B6 5BA,SO23 9AP,PO1 3AX,BFPO 61", "key": "GB", "zip": "GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}", "require": "ACZ", "state_name_type": "county", "id": "data/GB", "posturl": "http://www.royalmail.com/postcode-finder", "locality_name_type": "post_town", "fmt": "%N%n%O%n%A%n%C%n%S%n%Z", "name": "UNITED KINGDOM"}
```
Postocode Regex should be:
```
"zip": "GIR[ ]0AA ......"
```
instead of:
```
"zip": "GIR[ ]?0AA ......"
```

**Comment by dlyongemallo** [comment]
The regular expression is used for input validation. We are not going to reject "GIR0AA" because it's clearly intended to be "GIR 0AA".
