### ISSUE TITLE
AD has Parishes but is not defined in state_name_type

### ISSUE THREAD

**Issue by nngOpenStack** [googlei18n/libaddressinput#98]
According to https://en.wikipedia.org/wiki/Parishes_of_Andorra, the following are Parishes of AD.   But state_name_type is not defined as parish in http://i18napis.appspot.com/address/data/AD

data/AD/Canillo 
data/AD/Encamp 
data/AD/Escaldes-Engordany 
data/AD/La Massana 
data/AD/Ordino 
data/AD/Parròquia d'Andorra la Vella 
data/AD/Sant Julià de Lòria

**Comment by lararennie** [comment]
This is because they aren't used in addresses, so we don't care what the label is. Note that "fmt" for Andorra doesn't contain %S.

We could even delete the /AD file.
