### ISSUE TITLE
Serbia (RS) should have post office code and postcode

### ISSUE THREAD

**Issue by mimckenna** [googlei18n/libaddressinput#99]
For Serbia, the postal requirements seem to be:
\<5 digit post office code> \<city name> \<6 digit postcode>
The trailing postcode is optional if going to a PO Box.
"Beograd/11000" is not a valid address, but "11000 Beograd" is if going to a PO Box

i18napis has:
`"zip": "\\d{5,6}", "fmt": "%N%n%O%n%A%n%Z %C"`

It seems it should be something like:
`"zip": "\\d{6}", "fmt": "%N%n%O%n%A%n%X %C / %Z"`

Sources: Universal Postal Union [(UPU) guidelines for Serbia](http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/srbEn.pdf)
Serbian Postal Authority: http://www.posta.rs/struktura/eng/posalji/pismo-adresovanje.asp
Original Serbian guidelines: http://www.posta.rs/struktura/lat/posalji/pismo-adresovanje.asp

**Comment by lararennie** [comment]
This has been a bit of a contentious issue. Talking to the Serbian
community, the consensus (~ 2 years ago) was that the new postal code
system was a complete failure and no one used it or knew about it. They
maintained that no one used the six digit codes at all. For that reason we
supported the old five digit system, but allowed six digits if people
really wanted to use the new ones.

You're right, we could use %X for one of them but we'd have to change
tooling to provide the right label for it, and it'd be good to know if the
situation has changed and it's actually used in Serbia now. Do you have
customers requesting this? Are there websites using both codes in their
addresses?

For Serbia, the postal requirements seem to be:
<5 digit post office code> <city name> <6 digit postcode>
The trailing postcode is optional if going to a PO Box.
"Beograd/11000" is not a valid address, but "11000 Beograd" is if going to
a PO Box

i18napis has:
"zip": "\\d{5,6}", "fmt": "%N%n%O%n%A%n%Z %C"

It seems it should be something like:
"zip": "\\d{6}", "fmt": "%N%n%O%n%A%n%X %C / %Z"

Sources: Universal Postal Union (UPU) guidelines for Serbia
<http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/srbEn.pdf>
Serbian Postal Authority:
http://www.posta.rs/struktura/eng/posalji/pismo-adresovanje.asp

—
Reply to this email directly or view it on GitHub
<https://github.com/googlei18n/libaddressinput/issues/99>.

**Comment by mimckenna** [comment]
Hi,

Thanks for your response.  We are working through all the countries we support and have been comparing to official sites, hence the reference to UPU and Serbian Post.  We usually try to corroborate with local sources, but I guess we felt the Serbian Post site in both English and Serbian was too convincing ;-)

So, after your response, I went hunting and found the Serbian Post Office was the ONLY place I could find the PAK code being used!  So I believe you when you say "new postal code system was a complete failure and no one used it or knew about it”.  Even other government offices, hospitals, and real-estate listings omit the PAK code.  I didn’t find a single instance of a 6-digit code being used, except as a separate PAK code.

Based on that, and the colloquial use of postcode in Serbia, it seems i18napis needs to either stay the same and ignore the Serbian Post requested PAK code
Stay the same: `"zip": "\\d{5,6}", "fmt": "%N%n%O%n%A%n%Z %C”`

Or, accommodate the PAK code, which may only be used for [Serbian Post](http://www.posta.rs/struktura/lat/posalji/pismo-adresovanje.asp) and [RATEL](http://www.ratel.rs/насловна_страница.84.html), 
Possible Change: `"zip": "\\d{5}", "sort":"\\d{6}", "fmt": "%N%n%O%n%A%n%Z %C PAK %X"`

But legacy data is already using the `%Z %C` format for both i18napis and us, and I'm not quite sure how to impose regex on sort codes, or how to hide `PAK` when the PAK code field is empty.  So ...
I think I will side with the current libaddressinput and i18napis and change our code to match.

Research:

## The Dream:

Serbian paper on converting old postcodes to PAK, May 2011 (page 1188)
http://ftn.uns.ac.rs/n301517051/broj-05 

Serbian Post Office Address:
http://www.posta.rs/struktura/lat/kontakt/postavite-pitanje.asp 
```
Javno preduzeće „Pošta Srbije”
Takovska 2, 11120 Beograd
PAK: 135403
```
Serbian Post Example:
![image](https://cloud.githubusercontent.com/assets/11297262/13337407/0924a81e-dbd0-11e5-811c-3c3c60deb5ba.png)

The Serbian Post and RATEL, the Serbian Telecommunications authority were the ONLY places I could find use of PAK in an address.

## Reality

Wikipedia list of postcodes – all 5 digits
* [https://sr.wikipedia.org/wiki/Списак_поштанских_бројева_у_Србији](https://sr.wikipedia.org/wiki/Списак_поштанских_бројева_у_Србији)

Complaints and comments on the new PAK postcode
* http://beobuild.rs/forum/viewtopic.php?t=1512 

Apartment listings in Belgrade:
* http://www.krstarica.com/cir/katalog/Biznis_i_ekonomija/Nekretnine/ 
* \<5 digits postcode> \<city name>
* `Лазе Костића 2, 21000 Нови Сад`
* `Далматинска 72, 11000 Београд`

AddressDoctor
* http://lookup.addressdoctor.com/lookup/default.aspx?lookup=1&lang=en&country=SRB 
* \<5 digit postcode> \<city name>
* No accommodation for 6-digit PAK
* Example:
```
Gornjomilanovacka 51
34111 Kragujevac-Aerodrom, Aerodrom, Kragujevac
Serbia
```

Hospital address
* http://www.bolnica015.org.rs/dokumenta/Oglas191115/Oglas191115.pdf
* `Пола Карана 4, 15000 Шабац, Република Србиjа`

International Trade Center in Serbia
* http://www.zis.gov.rs/upload/documents/pdf_sr/pdf/uloga_is.pdf (last page)
* Also, on their website [http://zis.gov.rs/o-zavodu/контакти.47.html](http://zis.gov.rs/o-zavodu/%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%B8.47.html) 
```
Кнегинbe Љубице 5, 11 000 Бeоград 
Република Србиjа
```
   or
```
11 000 Београд, Кнегиње Љубице 5
Република Србија
```

Online form for claiming debts from debtors
* http://www.komoraizvrsitelja.rs/?q=vesti/uputstvo-za-popunjavanje-obrazaca-1-3-u-procesu-ravnomerne-podele-predmeta-izvrsiteljima 
* Asks for address and postcode:
* АДРЕСА – адреса дужника
* ПОШТАНСКИ БРОЈ – поштански број места боравка дужника 
* Does not ask for PAK

Republic of Serbia Statistics Office
* http://webrzs.stat.gov.rs/WebSite/Public/PageView.aspx?pKey=282
* `Београд, Милана Ракића 5`   - Government office that doesn’t include postcode or PAK number

Post Express
* http://www.postexpress.rs/struktura/lat/kako-da/adresovanje-posiljke.asp 
* Example: http://www.postexpress.rs/slike/lat/cenovnik/nalog-za-uplatu.gif 
![image](https://cloud.githubusercontent.com/assets/11297262/13337683/b3eeb734-dbd1-11e5-8070-665cba43676c.png)
* \<5 digit postcode> \<city>

[Microsoft Office Support](https://support.office.com/sr-latn-rs/article/Kreiranje-i-štampanje-koverti-za-masovno-slanje-pošte-cbe8f512-5b2a-4be0-af39-b462cc40c73a)
* Address Block image
* \<5-digit code> \<city>
![image](https://cloud.githubusercontent.com/assets/11297262/13337603/441276ee-dbd1-11e5-87b4-e6eff8c5d979.png)
